- name: Deploy to Azure WebApp
  uses: azure/webapps-deploy@v2
  with:
    app-name: leukemiaclassifier
    slot-name: production
    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    package: .